#define GSM_STACK_LIMIT     16
#define GSM_LIT_BUFFER_SIZE (1 << 16)
#define GSM_OUT_BUFFER_SIZE (1 << 14)

/*/doc

Virtual stack-based machine used for generating output in form of raw bytes.
Output is generated by performing series of steps. Each step is supplied to the machine
one at a time in the form of token.

There are 8 different kinds of tokens. Each token is responsible for different operation
inside the machine.
*/
typedef struct {
    // Buffer which holds raw data of recently used literal values.
    // Operates on the principle of circular buffer.
    u8 lit_buf[GSM_LIT_BUFFER_SIZE];

    // Buffer for storing produced output before writing it to {out}.
    u8 out_buf[GSM_OUT_BUFFER_SIZE];

    // Stack which holds "scratch" strings which are used later for writing output.
    str stack[GSM_STACK_LIMIT];

    // Produced output will be written here.
    Writer out;

    // Number of elements in the stack.
    uint stack_pos;

    // Number of bytes currently stored in output buffer.
    uint out_buf_pos;

    // Literal buffer next write position.
    uint lit_buf_pos;

    // Number of bytes currently stored inside literal buffer.
    uint lit_buf_len;
} GenStackMachine;

/*/doc

Adds string to literal buffer. Handles circular buffer logic.
*/
static void
gsm_lit_buf_add(GenStackMachine* m, str s) {

}

// Put literal directly into output.
#define GSM_TOKEN_PUT_LIT 0x0

// Put reference directly into output.
#define GSM_TOKEN_PUT_REF 0x1

typedef struct {
    str lit;
} GenStackMachineTokenDataPutLit;

typedef struct {
    uint offset;
    uint len;
} GenStackMachineTokenDataPutRef;

typedef union {
    GenStackMachineTokenDataPutLit put_lit;
    GenStackMachineTokenDataPutRef put_ref;
} GenStackMachineTokenData;

typedef struct {
    GenStackMachineTokenData data;

    // Opcode and discriminator for {data} union field.
    u8 kind;
} GenStackMachineToken;

static ErrorCode
gsm_step_put_lit(GenStackMachine* m, GenStackMachineToken* t) {
    return 0;
}

static ErrorCode
gsm_step_put_ref(GenStackMachine* m, GenStackMachineToken* t) {
    return 0;
}

static ErrorCode
gsm_step(GenStackMachine* m, GenStackMachineToken* t) {
    switch (t->kind) {
    case GSM_TOKEN_PUT_LIT:
        return gsm_step_put_lit(m, t);
    case GSM_TOKEN_PUT_REF:
        return gsm_step_put_ref(m, t);
    default:
        panic_trap();
    }
    return 0;
}
